version     = "0.1.0"
author      = "Softmax"
description = "Factory Commons — three cogs, one machine, and a lever that pays you now and costs everyone forever."
license     = "MIT"

srcDir = "src"

requires "nim >= 2.2.4"
requires "bitworld >= 0.1.0"
requires "pixie"
requires "mummy >= 0.4.7"
requires "whisky >= 0.1.3"
requires "curly >= 1.1.1"
requires "supersnappy >= 2.1.3"
requires "flatty >= 0.3.4"
